version: OpenSSL-Fips-{branch}.{build}

os: Visual Studio 2015

clone_folder: C:\OpenSSL
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:

environment:
  matrix:
    - platform:        "x86"
      vcversion:       "vc15"
      vstudio:         "VS2017"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"
    - platform:        "x64"
      vcversion:       "vc15"
      vstudio:         "VS2017"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"

install:
  - cd
  - dir
  - cd AppVeyor
  - Install.cmd %openssl_version% %fips_version%
  - cd

artifacts:
  - path: "*.zip"

build_script:
  - cd \OpenSSL\AppVeyor
  - Build.cmd %openssl_version% %fips_version% %platform% %vcversion% %vstudio%

test: off
