version: OpenSSL-Fips-{branch}.{build}

os: Visual Studio 2013

clone_folder: C:\OpenSSL
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: false

cache:

environment:
  matrix:
    - platform:        "x86"
      toolset:         "v110"
      vstudio:         "VS2012"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"
    - platform:        "x64"
      toolset:         "v110"
      vstudio:         "VS2012"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"
    - platform:        "x86"
      toolset:         "v90"
      vstudio:         "VS2008"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"
    - platform:        "x64"
      toolset:         "v90"
      vstudio:         "VS2008"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"

install:
  - cd
  - dir
  - cd AppVeyor
  - Install.cmd %openssl_version% %fips_version%
  - cd

artifacts:

build_script:
  - cd \OpenSSL\AppVeyor
  - Build.cmd %openssl_version% %fips_version% %platform% %toolset% %vstudio%

test: off
