version: OpenSSL-Fips-{branch}.{build}

os: Visual Studio 2013

clone_folder: C:\OpenSSL
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:

environment:
  matrix:
    - platform: "x86"
      vstudio:  "VS2013"
      toolset:  "v120"
      openssl_version: "1.0.2n"
      fips_version:    "2.0.16"

install:
  - cd AppVeyor
  - Install.cmd %openssl_version% %fips_version%
  - cd ..
  - pwd

artifacts:

build_script:
  - cd AppVeyor

test: off
