version: OpenSSL-Fips-{branch}.{build}

os: Visual Studio 2015

clone_folder: C:\OpenSSL
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: false

cache:

environment:
  matrix:
    - platform:        "x86"
      vcversion:       "vc9"
      vstudio:         "VS2008"
      openssl_version: "1.0.2o"
      fips_version:    "2.0.16"

    - platform:        "x86"
      vcversion:       "vc11"
      vstudio:         "VS2012"
      openssl_version: "1.0.2o"
      fips_version:    "2.0.16"
    - platform:        "x64"
      vcversion:       "vc11"
      vstudio:         "VS2012"
      openssl_version: "1.0.2o"
      fips_version:    "2.0.16"

    - platform:        "x86"
      vcversion:       "vc14"
      vstudio:         "VS2015"
      openssl_version: "1.0.2o"
      fips_version:    "2.0.16"
    - platform:        "x64"
      vcversion:       "vc14"
      vstudio:         "VS2015"
      openssl_version: "1.0.2o"
      fips_version:    "2.0.16"
install:
  - cd
  - cd AppVeyor
  - Install.cmd %openssl_version% %fips_version% %platform%
  - cd

artifacts:
  - path: "*.zip"

build_script:
  - cd \OpenSSL\AppVeyor
  - Build.cmd %openssl_version% %fips_version% %platform% %vcversion% %vstudio%

before_test:
  - cd \OpenSSL-dev\openssl-1.0.2o

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - nmake -f ms\ntdll.mak test && nmake -f ms\nt.mak test
